//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_EntityFramework_Assignment2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusInformation
    {
        public int BusID { get; set; }
        public string BoardingPoint { get; set; }
        public Nullable<System.DateTime> TravelDate { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<int> Rating { get; set; }
        public string DroppingPoint { get; set; }
    }
}
